namespace ICD.Connect.Cameras.Visca
{
	public enum eViscaResponse
	{
		OK,
		MESSAGE_LENGTH_ERROR,
		SYNTAX_ERROR,
		COMMAND_BUFFER_FULL,
		COMMAND_CANCELLED,
		NO_SOCKET,
		NOT_EXECUTABLE,
		UNSPECIFIED,
		NULL,
		IMPROPER_FORMAT
	}
}